import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: false })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('console', msg => { if (msg.type()==='error') console.log(`[${msg.type()}]`, msg.text()) })
page.on('pageerror', err => console.log('[pageerror]', err.message))
await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded', timeout: 60000 })
await page.bringToFront()
await page.waitForTimeout(3000)
await page.locator('nav[aria-label="Sections"] >> text=Projects').click({ timeout: 15000 })
await page.waitForTimeout(1500)
await page.screenshot({ path: '/tmp/final-zone.png' })
const slots = page.locator('li[class*="bigProjectModelSlot"]')
console.log('slots:', await slots.count())
const b0 = await slots.nth(0).boundingBox()
console.log('slot0', JSON.stringify(b0))
await page.mouse.move(b0.x + b0.width/2, b0.y + b0.height/2, { steps: 10 })
await page.waitForTimeout(900)
await page.screenshot({ path: '/tmp/final-hover.png' })
await browser.close()
